require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
